=== chuckwolber/cctools/ccct/ccct.schema.json
{
	"$schema": "https://json-schema.org/draft/2020-12/schema#",
	"type": "object",
	"properties": {
		"credential_dir": {
			"description": "Google sheets credential directory.",
			"type": "string"
		},
		"bank_id": {
			"description": "Your bank's ABA routing number.",
			"type": "integer"
		},
		"document_id": {
			"description": "Google Sheets spreadsheet document ID.",
			"type": "string"
		},
		"alloc_columns": {
			"description": "Spreadsheet columns to allocate transactions to.",
			"type": "array",
			"minItems": 1,
			"uniqueItems": true,
			"items": {
				"type": "object",
				"properties": {
					"short": {
						"type": "string"
					},
					"long": {
						"type": "string"
					}
				},
				"required": [
		  			"short",
					"long"
				]
	      		}
		}
	}
}

=== chuckwolber/cctools/ccct/ccct-example.json
{
	"credential_dir": "~/.google",
	"bank_id": 123456789,
	"document_id": "2CZrPH3M-Lg-TmD5luXu7loG3svABgfGP23txXbar7dg",
	"alloc_columns": [{
		"short": "ap",
		"long": "Amazon Purchases"
	},{
		"short": "pc",
		"long": "Petcare"
	},{
		"short": "af",
		"long": "Auto Fuel"
	},{
		"short": "af",
		"long": "Auto Fuel"
	}]
}
